index:
    path: /
    controller: App\Controller\DefaultController::index
about:
    path: /qui-sommes-nous
    controller: App\Controller\AboutController::about
vision:
    path: /notre-vision
    controller: App\Controller\VisionController::vision
strategie:
    path: /strategie-manageriale
    controller: App\Controller\StrategieController::strategie
contact:
    path: /contact
    controller: App\Controller\ContactController::contact
motpdg:
    path: /mot-du-pdg
    controller: App\Controller\MotPdgController::motpdg
service-telecommunication:
    path: /services/telecommunication
    controller: App\Controller\ServiceController::telecommunication
service-batiment:
    path: /services/batiment-et-travaux-publics
    controller: App\Controller\ServiceController::batiment
service-electricite:
    path: /services/electricite
    controller: App\Controller\ServiceController::electricite
